### ISSUE TITLE
Getting Traceback while trying to create new model.

### ISSUE THREAD

**Issue by falkartis** [HyperGAN/HyperGAN#163]
When I run `hypergan new modeldeprova` I'm getting following Traceback, now I don't know how to proceed. 

```
Traceback (most recent call last):
  File "/home/artis/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/artis/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/artis/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 7, in <module>
    import hypergan as hg
  File "/home/artis/.local/lib/python3.5/site-packages/hypergan/__init__.py", line 2, in <module>
    from .gan import GAN
  File "/home/artis/.local/lib/python3.5/site-packages/hypergan/gan.py", line 1, in <module>
    from hypergan.gans.standard_gan import StandardGAN
  File "/home/artis/.local/lib/python3.5/site-packages/hypergan/gans/standard_gan.py", line 10, in <module>
    from hypergan.discriminators import *
  File "/home/artis/.local/lib/python3.5/site-packages/hypergan/discriminators/autoencoder_discriminator.py", line 1, in <module>
    import tensorflow as tf
  File "/home/artis/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/artis/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/artis/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/artis/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/artis/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/artis/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by martyn** [comment]
Tensorflow error, will be fixed in 1.0.
