### ISSUE TITLE
Trying to run an old model results in an error

### ISSUE THREAD

**Issue by ProGamerGov** [HyperGAN/HyperGAN#171]
```
ubuntu@ip-Address:~$ hypergan train faceCrop/ -s 128x128x3 -f png -b 32 --config rmsprop-lsgan --sample_every 5
[loader] ImageLoader found 8003 images with 4 different class labels
Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 90, in <module>
    gan = hg.GAN(config=config, inputs=inputs)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/gan.py", line 14, in gan_factory
    return StandardGAN(*args, **kw_args)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/gans/standard_gan.py", line 43, in __init__
    BaseGAN.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/gans/base_gan.py", line 30, in __init__
    GANComponent.__init__(self, self, config)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/gan_component.py", line 33, in __init__
    self.create_ops(config)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/gan_component.py", line 43, in create_ops
    self.ops = self.gan.ops_backend(config=self.config, device=self.gan.device)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/ops/tensorflow/ops.py", line 19, in __init__
    self.dtype = self.parse_dtype(dtype)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/ops/tensorflow/ops.py", line 107, in parse_dtype
    raise Exception("dtype not defined: "+str(dtype))
Exception: dtype not defined: {'_type_enum': 1}

```

**Comment by martyn** [comment]
Hi, this may be related to older versions of hypergan.  0.10 does not support old models but new models will not experience this issue.
