### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Dqu1J** [HyperGAN/HyperGAN#196]
bash$ hypergan new mc
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "c:\users\user\appdata\local\programs\python\python~2\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\Scripts\\hypergan", line 7, in <module>
    import hypergan as hg
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\hypergan\__init__.py", line 2, in <module>
    from .gan import GAN
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\hypergan\gan.py", line 1, in <module>
    from hypergan.gans.standard_gan import StandardGAN
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\hypergan\gans\standard_gan.py", line 10, in <module>
    from hypergan.discriminators import *
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\hypergan\discriminators\autoencoder_discriminator.py", line 1, in <module>
    import tensorflow as tf
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\python\__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "c:\users\user\appdata\local\programs\python\python~2\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "c:\users\user\appdata\local\programs\python\python~2\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named '_pywrap_tensorflow'

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by Snaperkids** [comment]
To run TensorFlow you need to use Python 3.6.

**Comment by kabob8933** [comment]
`sudo apt install python3`
`sudo pip3 install tensorflow`

**Comment by martyn** [comment]
0.10 is out, let us know if this is still an issue
