### ISSUE TITLE
Support For TensorFlow > 2.0 (considering it is difficult to install compatible versions of tf)

### ISSUE THREAD

**Issue by LivelyCarpet87** [HyperGAN/HyperGAN#258]
It appears that HyperGAN is not compatible with the latest versions of tensorflow 2. The following is the output / error message when I try to train a model on a folder of images. Help would be much appreciated.

2020-06-29 01:28:31.932986: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-29 01:28:31.985086: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-29 01:28:31.985449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:07:00.0 name: GeForce RTX 2070 SUPER computeCapability: 7.5
coreClock: 1.785GHz coreCount: 40 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2020-06-29 01:28:31.985545: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-06-29 01:28:31.985575: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory
2020-06-29 01:28:31.985602: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2020-06-29 01:28:31.985627: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2020-06-29 01:28:31.985653: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2020-06-29 01:28:31.985679: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
2020-06-29 01:28:32.115486: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-29 01:28:32.115524: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-06-29 01:28:32.118110: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-29 01:28:32.153924: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3600070000 Hz
2020-06-29 01:28:32.154562: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb89c000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-29 01:28:32.154588: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-29 01:28:32.158486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-29 01:28:32.158503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      
Shuffling data
Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 99, in <module>
    inputs.create(args.directory,
  File "/usr/local/lib/python3.8/dist-packages/hypergan/inputs/image_loader.py", line 66, in create
    dataset = dataset.map(parse_function, num_parallel_calls=4)
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1623, in map
    return ParallelMapDataset(
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4016, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3221, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2531, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2496, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2657, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3214, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3156, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 265, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /usr/local/lib/python3.8/dist-packages/hypergan/inputs/image_loader.py:41 parse_function  *
        image_string = tf.read_file(filename)

**Comment by TheUltimateKerbonaut** [comment]
Yep, I'm getting the same problem

**Comment by TheUltimateKerbonaut** [comment]
This should really be renamed "Support Tensorflow >2.0" or something

**Comment by martyn** [comment]
The develop branch of hypergan has been re-written in pytorch. We're still getting it ready for general release.
