### ISSUE TITLE
StyleGAN2 Error on "resize -1" line in config

### ISSUE THREAD

**Issue by jjennings955** [HyperGAN/HyperGAN#261]
https://github.com/HyperGAN/HyperGAN/blob/282c2d5702725807d2dd047ba82ae90a6550960b/hypergan/configurations/stylegan2/stylegan54.json#L47

Error message:
```Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 135, in <module>
    gancli.run()
  File "/usr/local/lib/python3.6/dist-packages/hypergan/cli.py", line 190, in run
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/hypergan/cli.py", line 126, in train
    self.gan = hg.GAN(config=self.gan_config, inputs=self.create_input())
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gan.py", line 12, in gan_factory
    return GANComponent.lookup_function(None, config['class'])(*args, **kw_args)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gans/standard_gan.py", line 45, in __init__
    BaseGAN.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gans/base_gan.py", line 36, in __init__
    self.create()
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gans/standard_gan.py", line 58, in create
    self.generator = self.create_component("generator", input=self.latent)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gans/base_gan.py", line 99, in create_component
    gan_component = klass(self, defn, *args, **kw_args)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/discriminators/configurable_discriminator.py", line 13, in __init__
    ConfigurableComponent.__init__(self, gan, config,*args, **kw_args)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/configurable_component.py", line 143, in __init__
    GANComponent.__init__(self, gan, config)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gan_component.py", line 36, in __init__
    self.create()
  File "/usr/local/lib/python3.6/dist-packages/hypergan/configurable_component.py", line 159, in create
    net = self.create_parsed_layer(layer)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/configurable_component.py", line 166, in create_parsed_layer
    parsed, layer = self.parse_layer(layer_defn)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/configurable_component.py", line 177, in parse_layer
    layer = self.build_layer(parsed.layer_name, parsed.args, parsed.parsed_options)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/configurable_component.py", line 195, in build_layer
    net = self.layer_ops[op](None, args, options)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/configurable_component.py", line 411, in layer_reshape
    dims_args = [int(x) for x in args[0].split("*")]
AttributeError: 'int' object has no attribute 'split'
Error detected, HyperGAN exiting
```
When I try to train using the stylegan54.conf configuration file, I get the error message seen above.

This was the command I used to train:
`hypergan train ./images -b 16 -s 128x128x3 --resize -c stylegan54 --sample_every 5 --save_samples`

**Comment by martyn** [comment]
Thanks for trying out HG 1.0! 1.0RC1 is not compatible with configuration files before RC1. Major version releases such as 0.10 vs 1.0 can break configuration file compatibility, but configurations will stay compatible within a major version.

I'll add a more helpful error message here.

We actually have all the layers necessary for a new stylegan configuration but don't have a current configuration for it. It was much slower(due to the modulated_conv) - I don't mind adding one however.

Dev actions needed to resolve ticket: add stylegan.json and check configuration file version.

**Comment by martyn** [comment]
After researching we discovered that stylegan54.json was accidentally still in our configurations directory. This has been removed and version checking has been added. We can track stylegan progress in the linked MR.
