### ISSUE TITLE
--device cpu doesn't work

### ISSUE THREAD

**Issue by martyn** [HyperGAN/HyperGAN#276]
This flag in general doesn't work correctly since the move to pytorch.

CPU training should error out. We should consider making CPU sampling work however.

**Comment by martyn** [comment]
Feature request: CPU training should work with a warning

**Comment by martyn** [comment]
This is now `-B cpu`

**Comment by kahveciderin** [comment]
```hypergan: error: unrecognized arguments: -B cpu
Traceback (most recent call last):
  File "/home/derin/.local/bin/hypergan", line 68, in <module>
    args = CommandParser().get_parser().parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1783, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python3.8/argparse.py", line 2533, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.8/argparse.py", line 2520, in exit
    _sys.exit(status)
SystemExit: 2
Error detected, HyperGAN exiting
```
cloned the repo
