### ISSUE TITLE
Cannot find module elastic_weight_consolidation_optimizer on train

### ISSUE THREAD

**Issue by moritzsalla** [HyperGAN/HyperGAN#288]
HyperGAN keeps throwing this error (on colab) when I train `hypergan train data/ -c mymodel  -s 64x64x3 -b 8 --sample_every 10`, or with similar flags.

```
ModuleNotFoundError: No module named 'hypergan.optimizers.elastic_weight_consolidation_optimizer'
``` 

I believe I've installed everything correctly, `!hypergan new . -l` returns a list of possible configurations.

**Steps to reproduce the behaviour**

```
!pip3 install hypergan
```

I've had to install the following manually
```
!pip3 install hyperchamber --upgrade --force-reinstall
!pip3 install semantic_version --upgrade --force-reinstall
```

```
!hypergan new mymodel -c dcgan
```

```
!hypergan train data/ --sampler static_batch -b 8 --config mymodel
```

<details>
  <summary>Error message</summary>
Loading configuration /content/drive/My Drive/Colab Notebooks/stylegan2-ada/unused-data/mymodel.json
Creating component: latent
Creating component: generator
Creating component: discriminator
Creating component: loss
Creating component: trainer
Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 141, in <module>
    gancli.run()
  File "/usr/local/lib/python3.6/dist-packages/hypergan/cli.py", line 190, in run
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/hypergan/cli.py", line 126, in train
    self.gan = hg.GAN(config=self.gan_config, inputs=self.create_input())
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gan.py", line 12, in gan_factory
    return GANComponent.lookup_function(None, config['class'])(*args, **kw_args)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gans/standard_gan.py", line 45, in __init__
    BaseGAN.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gans/base_gan.py", line 36, in __init__
    self.create()
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gans/standard_gan.py", line 61, in create
    self.trainer = self.create_component("trainer")
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gans/base_gan.py", line 99, in create_component
    gan_component = klass(self, defn, *args, **kw_args)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/trainers/base_trainer.py", line 10, in __init__
    GANComponent.__init__(self, gan, config)
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gan_component.py", line 36, in __init__
    self.create()
  File "/usr/local/lib/python3.6/dist-packages/hypergan/trainers/base_trainer.py", line 38, in create
    result = self._create()
  File "/usr/local/lib/python3.6/dist-packages/hypergan/trainers/alternating_trainer.py", line 13, in _create
    self.d_optimizer = self.create_optimizer("d_optimizer")
  File "/usr/local/lib/python3.6/dist-packages/hypergan/trainers/base_trainer.py", line 47, in create_optimizer
    klass = GANComponent.lookup_function(None, defn['class'])
  File "/usr/local/lib/python3.6/dist-packages/hypergan/gan_component.py", line 92, in lookup_function
    return getattr(importlib.import_module(namespace),method)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hypergan.optimizers.elastic_weight_consolidation_optimizer'
Error detected, HyperGAN exiting
</details>

## System
 - Colab, GPU
 - Python 3.6.9
 - Pip 19.3.1

<details>
  <summary> Configuration File</summary>
{
    "class": "function:hypergan.losses.standard_loss.StandardLoss",
    "reduce": "reduce_mean"
  },
  "trainer": {
    "class": "function:hypergan.trainers.alternating_trainer.AlternatingTrainer",
    "g_optimizer": {

      "class": "function:hypergan.optimizers.elastic_weight_consolidation_optimizer.ElasticWeightConsolidationOptimizer",
      "f_decay": 0.8,
      "optimizer": {
        "class": "function:hypergan.optimizers.giga_wolf_optimizer.GigaWolfOptimizer",

        "optimizer": {
          "class": "function:tensorflow.python.training.adam.AdamOptimizer",
          "learn_rate": 1e-4,
          "beta1":0.0,
          "beta2":0.999
        },
        "optimizer2": {
          "class": "function:tensorflow.python.training.adam.AdamOptimizer",
          "learn_rate": 3e-5,
          "beta1":0.0,
          "beta2":0.999
        }
      }
    },
    "d_optimizer": {
      "class": "function:hypergan.optimizers.elastic_weight_consolidation_optimizer.ElasticWeightConsolidationOptimizer",
      "optimizer": {

        "class": "function:hypergan.optimizers.giga_wolf_optimizer.GigaWolfOptimizer",

        "optimizer": {
          "class": "function:tensorflow.python.training.adam.AdamOptimizer",
          "learn_rate": 1e-4,
          "beta1":0.0,
          "beta2":0.999
        },
        "optimizer2": {
          "class": "function:tensorflow.python.training.adam.AdamOptimizer",
          "learn_rate": 3e-5,
          "beta1":0.0,
          "beta2":0.999
        }
      }
    }
  },
  "runtime": {
    "channels": 3,
    "width": 64,
    "height": 64,
    "train": "hypergan train [dataset] --sampler static_batch -b 8"
  },

  "hypergan_version": "~1",
  "class": "class:hypergan.gans.standard_gan.StandardGAN"

}
</details>

**Comment by Musaddiqua** [comment]
Hi @moritzsalla 👋  

I’ve submitted a pull request that addresses this issue by adding the missing minibatch layer, implementing the Elastic Weight Consolidation optimizer, and including related tests.

PR reference: solves #288  

Please let me know if any changes or improvements are required.  
Thanks!

**Comment by moritzsalla** [comment]
This looks great, thanks! Nothing else required.

**Comment by Musaddiqua** [comment]
Hi @moritzsalla,

Thank you for the feedback—I’m glad the fix worked well.

I’m currently preparing for Google Summer of Code, and as part of
showcasing my open-source contributions, I wanted to ask if it would be
okay to share this contribution on LinkedIn. I will clearly credit the
HyperGAN project and reference the repository appropriately.

Please let me know if you’re comfortable with this.

Thanks again for your support.

Best regards,
Musaddiqua Rajannavar

**Comment by moritzsalla** [comment]
Hi @Musaddiqua, you'd have to ask one of the library authors :)

**Comment by martyn** [comment]
This configuration nests EWC and GigaWolf around TensorFlow Adam in the partially migrated runtime. Restoring one import would not validate that whole algorithm. The report and later contribution discussion are preserved; that optimizer stack was retired in favor of [#301](https://github.com/HyperGAN/HyperGAN/pull/301)'s explicit ParticleGAN loop.

Closing as superseded, not as an EWC implementation or a fix published to the old pip release. Current installed-package tests exercise real updates and reject unavailable constructors without dummy fallbacks. Old models require their [archived runtime](https://github.com/HyperGAN/HyperGAN/blob/develop/docs/migration.md); EWC would need a separately qualified continual-learning recipe.

Audit record: [individual disposition and retained work](https://github.com/HyperGAN/HyperGAN/blob/f4053ae1/reports/issue-audit-2026-09-18.md), published in #302.
